import { Nunito } from "next/font/google";
import "./globals.css";
import Dashboard from "./dashboard/page.js";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div>
          {children}
          <Dashboard />
        </div>
      </body>
    </html>
  );
}
